[[UNRESOLVED_REF]]
id = "TWEAKXL_11103"
span_starts_with = "TweakXL"
message = "Install TweakXL 1.11.3 or higher"

[[UNRESOLVED_REF]]
id = "TWEAKXL_11103"
span_starts_with = "TweakDBManager"
message = "Install TweakXL 1.11.3 or higher"

[[UNRESOLVED_REF]]
id = "CODEWARE_12001"
span_starts_with = "Codeware"
message = "Install Codeware 1.20.1 or higher"
